---
- name: "Deploy docker category_service"
  become: true
  docker_container:
    name: "{{ category_service_docker_name }}"
    hostname: "{{ category_service_docker_name }}"
    state: "started"
    image: "{{ category_service_docker_image }}"
    ports:
      - "{{ category_service_docker_ports }}"
    log_driver: "json-file"
    log_options:
      max-size: "10m"
      max-file: "3"
    restart_policy: "always"
    env:
      TZ: "Europe/Moscow"
      CATEGORY_PORT: "{{ category_service_port }}"
