---
- name: "Deploy docker pipeline_service"
  become: true
  docker_container:
    name: "{{ pipeline_service_docker_name }}"
    hostname: "{{ pipeline_service_docker_name }}"
    state: "started"
    image: "{{ pipeline_service_docker_image }}"
    ports:
      - "{{ pipeline_service_docker_ports }}"
    log_driver: "json-file"
    log_options:
      max-size: "10m"
      max-file: "3"
    restart_policy: "always"
    env:
      TZ: "Europe/Moscow"
      PIPELINE_PORT: "{{ pipeline_service_port }}"
